name: npm audit fix

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  npm-audit-fix:
    name: (api) npm audit --production
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: YOUR_USERNAME/npm-audit-fix-action@main
